[package]
name = "rkcp"
version = "0.1.0"
authors = ["xChen16 <ares_0427@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
